server:
  port: 8120
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-sms # 服务名
#  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/srb_core?serverTimezone=GMT%2B8&characterEncoding=utf-8
#    username: root
#    password: root
  redis:
    host: localhost
    port: 6379
    database: 0
    #password: root
    timeout: 3000ms
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 8
        min-idle: 0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#mybatis-plus:
#  mapper-locations: classpath:com/atguigu/srb/core/mapper/xml/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
    ##  level:
    ##    root: debug
aliyun:
  sms:
    region-id: cn-shenzhen
    key-id: LTAI5tRb4YGPDqRjuCEazQkL
    key-secret: s0wh0QRH5izJQ79PPeyAEGgAK7Xmzp
    template-code: SMS_217425770
    sign-name: 北京课时教育
feign:
  client:
    config:
      default:
        connectTimeout: 10000 #连接超时配置
        readTimeout: 600000 #执行超时配置
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.srb.sms.client.CoreUserInfoClient: DEBUG #以什么级别监控哪个接口